# Change these first
owner: credtechau # Your GitHub organization or username, where this repository lives
repo: credtech-monitor # The name of this repository

sites:
  - name: Wefund
    url: https://platform.wefund.io/login
  - name: Fundingtech [DEV]
    url: https://dev.fundingtech.io/login

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /credtech-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CREDTech Uptime
  introTitle: "CREDTech Service Status"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
