# Change these first
owner: credtechau # Your GitHub organization or username, where this repository lives
repo: credtech-monitor # The name of this repository

sites:
  - name: Wefund-FE [PROD]
    url: https://platform.wefund.io/login
  - name: Wefund-BE [PROD]
    url: https://platform.wefund.io/api/users/bdmList
  - name: Wefund-FE [STAGING]
    url: https://staging.wefund.io/login
  - name: Wefund-BE [STAGING]
    url: https://platform.wefund.io/api/users/bdmList
  - name: Wefund-FE [DEV]
    url: https://dev.wefund.io/login
  - name: Wefund-BE [DEV]
    url: https://dev.wefund.io/api/users/bdmList
  - name: Settletech-FE [DEV]
    url: https://dev.settletech.io/login
  - name: Settletech-BE [DEV]
    url: https://dev.settletech.io/api/metadata
  - name: Settletech-FE [STAGING]
    url: https://staging.settletech.io/login
  - name: Settletech-BE [STAGING]
    url: https://staging.settletech.io/api/metadata
  - name: Settletech-FE [PRODUCTION]
    url: https://platform.settletech.io/login
  - name: Settletech-BE [PRODUCTION]
    url: https://platform.settletech.io/api/metadata

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /credtech-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CREDTech Uptime
  introTitle: "CREDTech Service Status"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
